name       = "forgpt"
version    = "VERSION"
author     = "Seyed Ali Ghasemi"
maintainer = "info@gha3mi.com"
copyright  = "Copyright (c) 2023, Seyed Ali Ghasemi"
license    = "LICENSE"

[build]
auto-executables = false
auto-tests       = false
auto-examples    = false
module-naming    = false

[install]
library = true

[fortran]
implicit-typing   = false
implicit-external = false
source-form       = "free"

[dependencies]
http   = { git = "https://github.com/fortran-lang/http-client.git" }
stdlib = "*"