conversation – ForOpenAI
conversation Subroutine
Seyed Ali Ghasemi
26 statements
Source File
private impure elemental subroutine conversation(this, file_name_base, file_name_ChatCompletion, input_file, output_file, inputfile_command, exit_command)
Type Bound
ChatCompletion
Arguments
Type Intent Optional Attributes Name
class(ChatCompletion), intent(inout) :: this
character(len=*), intent(in) :: file_name_base
character(len=*), intent(in) :: file_name_ChatCompletion
character(len=*), intent(in) :: input_file
character(len=*), intent(in) :: output_file
character(len=*), intent(in) :: inputfile_command
character(len=*), intent(in) :: exit_command
Calls
Source Code
   elemental impure subroutine conversation(this, file_name_base, file_name_ChatCompletion, &
      input_file, output_file, inputfile_command, exit_command)
      class(ChatCompletion), intent(inout) :: this
      character(len=*), intent(in)         :: file_name_base
      character(len=*), intent(in)         :: file_name_ChatCompletion
      character(len=*), intent(in)         :: input_file
      character(len=*), intent(in)         :: output_file
      character(len=*), intent(in)         :: inputfile_command
      character(len=*), intent(in)         :: exit_command
      call this%set_base_data(file_name_base)
      call this%set(file_name_ChatCompletion)
      call this%init_messages(n=3)
      call this%messages(1)%set(role='system', content='You are a helpful assistant.')
      call this%messages(2)%set(role='assistant', content='')
      call this%messages(3)%set_role(role='user')
      do
         call this%read_user_message(file_name=trim(input_file), command=trim(inputfile_command))
         if (trim(this%get_user_message()) == trim(exit_command)) exit
         call this%create()
         call this%set_asisstant_response(response=this%get_assistant_response())
         call this%print_assistant_response()
         call this%write_history(file_name=trim(output_file))
      end do
      call this%usage%print_prompt_tokens()
      call this%usage%print_completion_tokens()
      call this%usage%print_total_tokens()
   end subroutine conversation
Call graph
conversation calls create_chat_completion, get_assistant_response, get_user_message, init_messages, print_assistant_response, print_completion_tokens, print_prompt_tokens, print_total_tokens, read_user_message, set_asisstant_response, set_base_data, set_chatcompletion_data, set_role, write_history
create_chat_completion calls set_asisstant_response, add, deserialize, destroy, get, initialize, pair_type, print_to_string, check_chat_completion, request
print_assistant_response calls colorize
read_user_message calls colorize, set_user_message
set_asisstant_response calls set_content
set_base_data calls load_api_key, load_organization, set_api_key, set_api_key_env, set_file_name, set_organization, set_organization_env
set_chatcompletion_data calls load_chatcompletion_data, set_file_name, set_frequency_penalty, set_max_tokens, set_model, set_n, set_presence_penalty, set_stream, set_temperature, set_top_p, set_url, set_user_name
write_history calls get_assistant_response, get_user_message
load_api_key calls destroy, get, initialize, set_file_name, load_file
load_chatcompletion_data calls set_file_name, load_frequency_penalty, load_max_tokens, load_model, load_n, load_presence_penalty, load_stream, load_temperature, load_top_p, load_url, load_user_name
load_organization calls destroy, get, initialize, set_file_name, load_file
set_api_key_env calls set_api_key
set_organization_env calls set_organization
set_user_message calls set_content
load_frequency_penalty calls destroy, get, initialize, load_file
load_max_tokens calls destroy, get, initialize, load_file
load_model calls destroy, get, initialize, load_file
load_n calls destroy, get, initialize, load_file
load_presence_penalty calls destroy, get, initialize, load_file
load_stream calls destroy, get, initialize, load_file
load_temperature calls destroy, get, initialize, load_file
load_top_p calls destroy, get, initialize, load_file
load_url calls destroy, get, initialize, load_file
load_user_name calls destroy, get, initialize, load_file