create_chat_completion – ForOpenAI
create_chat_completion Subroutine
Seyed Ali Ghasemi
70 statements
Source File
private subroutine create_chat_completion(this, msg, rsp, conversiation)
Uses
json_module
face
http
Type Bound
ChatCompletion
Arguments
Type Intent Optional Attributes Name
class(ChatCompletion), intent(inout) :: this
character(len=*), intent(in) :: msg
character(len=:), intent(out), allocatable :: rsp
logical, intent(in) :: conversiation
Calls
Contents
Source Code
create_chat_completion
Source Code
   subroutine create_chat_completion(this,msg,rsp,conversiation)
      use http,        only: response_type, request, HTTP_POST, pair_type
      use json_module, only: json_file
      use face,        only: colorize
      class(ChatCompletion),         intent(inout) :: this
      character(len=*),              intent(in)    :: msg
      logical,                       intent(in)    :: conversiation
      character(len=:), allocatable, intent(out)   :: rsp
      character(len=:), allocatable                :: jsonstr
      type(pair_type),  allocatable                :: req_header(:)
      type(response_type)                          :: response
      type(json_file)                              :: json
      logical                                      :: found
      integer                                      :: i
      character(len=10)                            :: i_str
      integer                                      :: error
      call this%check(error)
      if (error == 0) then
         if (conversiation) then
            do i = 1, size(this%messages)
               if (this%messages(i)%role == 'user') then
                  call this%messages(i)%set_content(trim(msg))
               end if
            end do
            call this%messages(3)%set(role='user', content=trim(msg))
         else
            do i = 1, size(this%messages)
               if (this%messages(i)%role == 'user') then
                  print "(A,': ',A)", colorize(trim(this%user_name), color_bg='green'), this%messages(2)%content
               end if
            end do
         end if
         req_header = [&
            pair_type('Content-Type', 'application/json'),&
            pair_type('Authorization', 'Bearer '//trim(this%api_key)//''),&
            pair_type('OpenAI-Organization', ' '//trim(this%organization)//'')&
            ]
         call json%add('model', trim(this%model))
         do i = 1, size(this%messages)
            write (i_str, "(I10)") i
            call json%add('messages('//trim(i_str)//').role', this%messages(i)%role)
            call json%add('messages('//trim(i_str)//').content', this%messages(i)%content)
            ! call json%add('messages('//trim(i_str)//').name', this%messages(i)%name)
         end do
         call json%add('user', trim(this%user_name))
         call json%add('temperature', this%temperature)
         call json%add('max_tokens', this%max_tokens)
         call json%print_to_string(jsonstr)
         response = request(&
            url = trim(this%url),&
            method = HTTP_POST,&
            data = jsonstr,&
            header = req_header)
         if (response%ok) then
            json = response%content
            call json%get("choices(1).finish_reason", this%finish_reason)
            call json%get("usage.prompt_tokens", this%usage%prompt_tokens)
            call json%get("usage.completion_tokens", this%usage%completion_tokens)
            call json%get("usage.total_tokens", this%usage%total_tokens)
            call json%get("choices(1).message.content", rsp, found=found)
            if (found) then
               print "(A,': ',A)", colorize("ChatGPT", color_bg='blue'), rsp
            else
               call json%get("error.message", jsonstr)
               print "(A,': ',A)", colorize("ChatGPT", color_bg='red'), jsonstr
            end if
         else
            print '(A)', 'Sorry, an error occurred while processing your request.'
            print '(A)', 'Error message:', response%err_msg
         end if
      end if
      if (conversiation) then
         do i = 1, size(this%messages)
            if (this%messages(i)%role == 'assistant') then
               call this%messages(i)%set_content(content=rsp)
            end if
         end do
      end if
   end subroutine create_chat_completion
Call graph
create_chat_completion calls add, check, colorize, get, messages, pair_type, print_to_string, request