create_image_edit – ForOpenAI
create_image_edit Subroutine
Seyed Ali Ghasemi
45 statements
Source File
private subroutine create_image_edit(this, image, mask, prompt, n, size, response_format, user_name)
Uses
json_module
http
Type Bound
ImageEdit
Arguments
Type Intent Optional Attributes Name
class(ImageEdit), intent(inout) :: this
character(len=*), intent(in) :: image
character(len=*), intent(in), optional :: mask
character(len=*), intent(in) :: prompt
integer, intent(in), optional :: n
character(len=*), intent(in), optional :: size
character(len=*), intent(in), optional :: response_format
character(len=*), intent(in), optional :: user_name
Calls
Contents
Source Code
create_image_edit
Source Code
   subroutine create_image_edit(this, image, mask, prompt, n, size, response_format, user_name)
      use http,        only: response_type, request, HTTP_POST, pair_type
      use json_module, only: json_file
      class(ImageEdit),       intent(inout)        :: this
      character(len=*),       intent(in)           :: image
      character(len=*),       intent(in)           :: prompt
      character(len=*),       intent(in), optional :: mask
      integer,                intent(in), optional :: n
      character(len=*),       intent(in), optional :: size
      character(len=*),       intent(in), optional :: response_format
      character(len=*),       intent(in), optional :: user_name
      character(len=:),       allocatable          :: assistant_response
      character(len=:),       allocatable          :: jsonstr
      type(pair_type),        allocatable          :: req_header(:), form_data(:), file_data
      type(response_type)                          :: response
      type(json_file)                              :: json
      logical                                      :: found
      integer                                      :: i
      character(len=10)                            :: i_str
      character(len=10)                          :: n_str
      call this%set_prompt(prompt=prompt)
      if (present(n)) call this%set_n(n=n)
      if (present(size)) call this%set_size(size=size)
      if (present(response_format)) call this%set_response_format(response_format=response_format)
      if (present(user_name)) call this%set_user_name(user_name=user_name)
      req_header = [&
         pair_type('Content-Type', 'multipart/form-data'),&
         pair_type('Authorization', 'Bearer '//trim(this%api_key)),&
         pair_type('OpenAI-Organization', ' '//trim(this%organization))&
         ]
      write(n_str, "(I10)") this%n
      form_data = [&
         pair_type('size', trim(this%size)),&
         pair_type('prompt', trim(this%prompt)),&
         pair_type('response_format', trim(this%response_format)),&
         pair_type('n', trim(n_str)),&
         pair_type('user', trim(this%user_name))&
         ]
      file_data =  pair_type('image', trim(this%image))
      response = request(url=trim(this%url), method=HTTP_POST, header=req_header, form=form_data, file=file_data)
      if (response%ok) then
         allocate(this%assistant_response(this%n))
         call json%initialize()
         call json%deserialize(response%content)
         do i = 1, this%n
            write (i_str, "(I10)") i
            call json%get("data("//trim(i_str)//").url", assistant_response, found=found)
            call this%set_assistant_response(assistant_response=assistant_response, i=i)
         end do
         call json%destroy()
      else
         print '(A)', 'Sorry, an error occurred while processing your request.'
         print '(A)', 'Error message:', response%err_msg
      end if
   end subroutine create_image_edit
Call graph
create_image_edit calls deserialize, destroy, get, initialize, pair_type, set_assistant_response, set_n, set_prompt, set_response_format, set_size, set_user_name, request