deallocate_openai – ForOpenAI
deallocate_openai Subroutine
Seyed Ali Ghasemi
6 statements
Source File
private pure elemental subroutine deallocate_openai(this)
Type Bound
openai
Arguments
Type Intent Optional Attributes Name
class(openai), intent(inout) :: this
Calls
Called by
Source Code
   elemental pure subroutine deallocate_openai(this)
      class(openai), intent(inout) :: this
      call this%deallocate_api_key()
      call this%deallocate_organization()
      call this%deallocate_file_name()
   end subroutine deallocate_openai
Call graph
deallocate_openai calls deallocate_api_key, deallocate_file_name, deallocate_organization
test_base calls deallocate_openai