deallocate_Translation – ForOpenAI
deallocate_Translation Subroutine
Seyed Ali Ghasemi
8 statements
Source File
private pure elemental subroutine deallocate_Translation(this)
Type Bound
Translation
Arguments
Type Intent Optional Attributes Name
class(Translation), intent(inout) :: this
Calls
Called by
Source Code
   elemental pure subroutine deallocate_Translation(this)
      class(Translation), intent(inout) :: this
      call this%deallocate_url()
      call this%deallocate_model()
      call this%deallocate_prompt()
      call this%deallocate_file()
      call this%deallocate_assistant_response()
   end subroutine deallocate_Translation
Call graph
deallocate_translation calls deallocate_assistant_response, deallocate_file, deallocate_model, deallocate_prompt, deallocate_url
test_translation calls deallocate_translation