deallocate_Transcription – ForOpenAI
deallocate_Transcription Subroutine
Seyed Ali Ghasemi
9 statements
Source File
private pure elemental subroutine deallocate_Transcription(this)
Type Bound
Transcription
Arguments
Type Intent Optional Attributes Name
class(Transcription), intent(inout) :: this
Calls
Called by
Source Code
   elemental pure subroutine deallocate_Transcription(this)
      class(Transcription), intent(inout) :: this
      call this%deallocate_url()
      call this%deallocate_model()
      call this%deallocate_language()
      call this%deallocate_prompt()
      call this%deallocate_file()
      call this%deallocate_assistant_response()
   end subroutine deallocate_Transcription
Call graph
deallocate_transcription calls deallocate_assistant_response, deallocate_file, deallocate_language, deallocate_model, deallocate_prompt, deallocate_url
test_transcription calls deallocate_transcription