get_assistant_response – ForOpenAI
get_assistant_response Function
Seyed Ali Ghasemi
10 statements
Source File
private pure function get_assistant_response(this) result(response)
Type Bound
ChatCompletion
Arguments
Type Intent Optional Attributes Name
class(ChatCompletion), intent(in) :: this
Return Value character(len=:), allocatable
Called by
Call graph
conversation calls get_assistant_response, write_history
write_history calls get_assistant_response