load_top_p – ForOpenAI
load_top_p Subroutine
Seyed Ali Ghasemi
12 statements
Source File
private impure elemental subroutine load_top_p(this)
Uses
json_module
Type Bound
ChatCompletion
Arguments
Type Intent Optional Attributes Name
class(ChatCompletion), intent(inout) :: this
Calls
Called by
Contents
Source Code
load_top_p
Source Code
   elemental impure subroutine load_top_p(this)
      use json_module, only: json_file
      class(ChatCompletion), intent(inout) :: this
      type(json_file)                      :: json
      real                                 :: tmp
      logical                              :: found
      call json%initialize()
      call json%load_file(trim(this%file_name))
      call json%get("ChatCompletion.top_p", tmp, found=found)
      if (found) this%top_p = tmp
      call json%destroy()
   end subroutine load_top_p
Call graph
load_top_p calls destroy, get, initialize, load_file
load_chatcompletion_data calls load_top_p