load_model – ForOpenAI
load_model Subroutine
Seyed Ali Ghasemi
9 statements
Source File
private impure elemental subroutine load_model(this)
Uses
json_module
Type Bound
ChatCompletion
Arguments
Type Intent Optional Attributes Name
class(ChatCompletion), intent(inout) :: this
Calls
Called by
Contents
Source Code
load_model
Source Code
   elemental impure subroutine load_model(this)
      use json_module, only: json_file
      class(ChatCompletion), intent(inout) :: this
      type(json_file)                      :: json
      call json%initialize()
      call json%load_file(trim(this%file_name))
      call json%get("ChatCompletion.model", this%model)
      call json%destroy()
   end subroutine load_model
Call graph
load_model calls destroy, get, initialize, load_file
load_chatcompletion_data calls load_model