load_presence_penalty – ForOpenAI
load_presence_penalty Subroutine
Seyed Ali Ghasemi
12 statements
Source File
private impure elemental subroutine load_presence_penalty(this)
Uses
json_module
Type Bound
ChatCompletion
Arguments
Type Intent Optional Attributes Name
class(ChatCompletion), intent(inout) :: this
Calls
Called by
Source Code
   elemental impure subroutine load_presence_penalty(this)
      use json_module, only: json_file
      class(ChatCompletion), intent(inout) :: this
      type(json_file)                      :: json
      real                                 :: tmp
      logical                              :: found
      call json%initialize()
      call json%load_file(trim(this%file_name))
      call json%get("ChatCompletion.presence_penalty", tmp, found=found)
      if (found) this%presence_penalty = tmp
      call json%destroy()
   end subroutine load_presence_penalty
Call graph
load_presence_penalty calls destroy, get, initialize, load_file
load_chatcompletion_data calls load_presence_penalty
set_chatcompletion_data calls load_chatcompletion_data
conversation calls set_chatcompletion_data
test_chatcompletion calls set_chatcompletion_data