load_user_name – ForOpenAI
load_user_name Subroutine
Seyed Ali Ghasemi
12 statements
Source File
private impure elemental subroutine load_user_name(this)
Uses
json_module
Type Bound
ImageGeneration
Arguments
Type Intent Optional Attributes Name
class(ImageGeneration), intent(inout) :: this
Calls
Called by
Contents
Source Code
load_user_name
Source Code
   elemental impure subroutine load_user_name(this)
      use json_module, only: json_file
      class(ImageGeneration), intent(inout) :: this
      type(json_file)                      :: json
      character(len=:), allocatable        :: tmp
      logical                              :: found
      call json%initialize()
      call json%load_file(trim(this%file_name))
      call json%get("ImageGeneration.user_name", tmp, found=found)
      if (found) this%user_name = trim(tmp)
      call json%destroy()
   end subroutine load_user_name
Call graph
load_user_name calls destroy, get, initialize, load_file
load_imagegeneration_data calls load_user_name