load_stream – ForOpenAI
load_stream Subroutine
Seyed Ali Ghasemi
12 statements
Source File
private impure elemental subroutine load_stream(this)
Uses
json_module
Type Bound
ChatCompletion
Arguments
Type Intent Optional Attributes Name
class(ChatCompletion), intent(inout) :: this
Calls
Called by
Source Code
   elemental impure subroutine load_stream(this)
      use json_module, only: json_file
      class(ChatCompletion), intent(inout) :: this
      type(json_file)                      :: json
      logical                              :: tmp
      logical                              :: found
      call json%initialize()
      call json%load_file(trim(this%file_name))
      call json%get("ChatCompletion.stream", tmp, found=found)
      if (found) this%stream = tmp
      call json%destroy()
   end subroutine load_stream
Call graph
load_stream calls destroy, get, initialize, load_file
load_chatcompletion_data calls load_stream
set_chatcompletion_data calls load_chatcompletion_data
conversation calls set_chatcompletion_data
test_chatcompletion calls set_chatcompletion_data