load_n – ForOpenAI
load_n Subroutine
Seyed Ali Ghasemi
12 statements
Source File
private impure elemental subroutine load_n(this)
Uses
json_module
Type Bound
ImageGeneration
Arguments
Type Intent Optional Attributes Name
class(ImageGeneration), intent(inout) :: this
Calls
Called by
Source Code
   elemental impure subroutine load_n(this)
      use json_module, only: json_file
      class(ImageGeneration), intent(inout) :: this
      type(json_file)                      :: json
      integer                              :: tmp
      logical                              :: found
      call json%initialize()
      call json%load_file(trim(this%file_name))
      call json%get("ImageGeneration.n", tmp, found=found)
      if (found) this%n = tmp
      call json%destroy()
   end subroutine load_n
Call graph
load_n calls destroy, get, initialize, load_file
load_imagegeneration_data calls load_n
set_imagegeneration_data calls load_imagegeneration_data
test_imagegeneration calls set_imagegeneration_data