load_Translation_data – ForOpenAI
load_Translation_data Subroutine
Seyed Ali Ghasemi
9 statements
Source File
private impure elemental subroutine load_Translation_data(this, file_name)
Type Bound
Translation
Arguments
Type Intent Optional Attributes Name
class(Translation), intent(inout) :: this
character(len=*), intent(in) :: file_name
Calls
Called by
Source Code
   elemental impure subroutine load_Translation_data(this, file_name)
      class(Translation), intent(inout) :: this
      character(len=*),   intent(in)    :: file_name
      call this%set_file_name(trim(file_name))
      call this%load_url()
      call this%load_model()
      call this%load_temperature()
      call this%load_response_format()
   end subroutine load_Translation_data
Call graph
load_translation_data calls load_model, load_response_format, load_temperature, load_url, set_file_name
load_model calls destroy, get, initialize, load_file
load_response_format calls destroy, get, initialize, load_file
load_temperature calls destroy, get, initialize, load_file
load_url calls destroy, get, initialize, load_file
set_translation_data calls load_translation_data
test_translation calls set_translation_data