load_size – ForOpenAI
load_size Subroutine
Seyed Ali Ghasemi
12 statements
Source File
private impure elemental subroutine load_size(this)
Uses
json_module
Type Bound
ImageGeneration
Arguments
Type Intent Optional Attributes Name
class(ImageGeneration), intent(inout) :: this
Calls
Called by
Contents
Source Code
load_size
Source Code
   elemental impure subroutine load_size(this)
      use json_module, only: json_file
      class(ImageGeneration), intent(inout) :: this
      type(json_file)                      :: json
      character(len=:), allocatable        :: tmp
      logical                              :: found
      call json%initialize()
      call json%load_file(trim(this%file_name))
      call json%get("ImageGeneration.size", tmp, found=found)
      if (found) this%size = trim(tmp)
      call json%destroy()
   end subroutine load_size
Call graph
load_size calls destroy, get, initialize, load_file
load_imagegeneration_data calls load_size