load_Transcription_data – ForOpenAI
load_Transcription_data Subroutine
Seyed Ali Ghasemi
10 statements
Source File
private impure elemental subroutine load_Transcription_data(this, file_name)
Type Bound
Transcription
Arguments
Type Intent Optional Attributes Name
class(Transcription), intent(inout) :: this
character(len=*), intent(in) :: file_name
Calls
Called by
Source Code
   elemental impure subroutine load_Transcription_data(this, file_name)
      class(Transcription), intent(inout) :: this
      character(len=*),     intent(in)    :: file_name
      call this%set_file_name(trim(file_name))
      call this%load_url()
      call this%load_model()
      call this%load_temperature()
      call this%load_language()
      call this%load_response_format()
   end subroutine load_Transcription_data
Call graph
load_transcription_data calls load_language, load_model, load_response_format, load_temperature, load_url, set_file_name
load_language calls destroy, get, initialize, load_file
load_model calls destroy, get, initialize, load_file
load_response_format calls destroy, get, initialize, load_file
load_temperature calls destroy, get, initialize, load_file
load_url calls destroy, get, initialize, load_file
set_transcription_data calls load_transcription_data
test_transcription calls set_transcription_data