load_temperature – ForOpenAI
load_temperature Subroutine
Seyed Ali Ghasemi
12 statements
Source File
private impure elemental subroutine load_temperature(this)
Uses
json_module
Type Bound
Translation
Arguments
Type Intent Optional Attributes Name
class(Translation), intent(inout) :: this
Calls
Called by
Source Code
   elemental impure subroutine load_temperature(this)
      use json_module, only: json_file
      class(Translation), intent(inout) :: this
      type(json_file)                   :: json
      real                              :: tmp
      logical                           :: found
      call json%initialize()
      call json%load_file(trim(this%file_name))
      call json%get("Translation.temperature", tmp, found=found)
      if (found) this%temperature = tmp
      call json%destroy()
   end subroutine load_temperature
Call graph
load_temperature calls destroy, get, initialize, load_file
load_translation_data calls load_temperature
set_translation_data calls load_translation_data
test_translation calls set_translation_data