load_max_tokens – ForOpenAI
load_max_tokens Subroutine
Seyed Ali Ghasemi
9 statements
Source File
private impure elemental subroutine load_max_tokens(this)
Uses
json_module
Type Bound
ChatCompletion
Arguments
Type Intent Optional Attributes Name
class(ChatCompletion), intent(inout) :: this
Calls
Called by
Source Code
   elemental impure subroutine load_max_tokens(this)
      use json_module, only: json_file
      class(ChatCompletion), intent(inout) :: this
      type(json_file)                      :: json
      call json%initialize()
      call json%load_file(trim(this%file_name))
      call json%get("ChatCompletion.max_tokens", this%max_tokens)
      call json%destroy()
   end subroutine load_max_tokens
Call graph
load_max_tokens calls destroy, get, initialize, load_file
load_chatcompletion_data calls load_max_tokens
set_chatcompletion_data calls load_chatcompletion_data
conversation calls set_chatcompletion_data
test_chatcompletion calls set_chatcompletion_data