load_ImageGeneration_data – ForOpenAI
load_ImageGeneration_data Subroutine
Seyed Ali Ghasemi
10 statements
Source File
private impure elemental subroutine load_ImageGeneration_data(this, file_name)
Type Bound
ImageGeneration
Arguments
Type Intent Optional Attributes Name
class(ImageGeneration), intent(inout) :: this
character(len=*), intent(in) :: file_name
Calls
Contents
Source Code
load_ImageGeneration_data
Source Code
   elemental impure subroutine load_ImageGeneration_data(this, file_name)
      class(ImageGeneration), intent(inout) :: this
      character(len=*),      intent(in)    :: file_name
      call this%set_file_name(trim(file_name))
      call this%load_url()
      call this%load_size()
      call this%load_response_format()
      call this%load_n()
      call this%load_user_name()
   end subroutine load_ImageGeneration_data
Call graph
load_imagegeneration_data calls load_n, load_response_format, load_size, load_url, load_user_name, set_file_name
load_n calls destroy, get, initialize, load_file
load_response_format calls destroy, get, initialize, load_file
load_size calls destroy, get, initialize, load_file
load_url calls destroy, get, initialize, load_file
load_user_name calls destroy, get, initialize, load_file