load_response_format – ForOpenAI
load_response_format Subroutine
Seyed Ali Ghasemi
12 statements
Source File
private impure elemental subroutine load_response_format(this)
Uses
json_module
Type Bound
Translation
Arguments
Type Intent Optional Attributes Name
class(Translation), intent(inout) :: this
Calls
Called by
Source Code
   elemental impure subroutine load_response_format(this)
      use json_module, only: json_file
      class(Translation), intent(inout) :: this
      type(json_file)                   :: json
      character(len=:), allocatable     :: tmp
      logical                           :: found
      call json%initialize()
      call json%load_file(trim(this%file_name))
      call json%get("Translation.response_format", tmp, found=found)
      if (found) this%response_format = trim(tmp)
      call json%destroy()
   end subroutine load_response_format
Call graph
load_response_format calls destroy, get, initialize, load_file
load_translation_data calls load_response_format
set_translation_data calls load_translation_data
test_translation calls set_translation_data