load_base_data – ForOpenAI
load_base_data Subroutine
Seyed Ali Ghasemi
7 statements
Source File
private impure elemental subroutine load_base_data(this, file_name)
Type Bound
openai
Arguments
Type Intent Optional Attributes Name
class(openai), intent(inout) :: this
character(len=*), intent(in) :: file_name
Calls
Contents
Source Code
load_base_data
Source Code
   elemental impure subroutine load_base_data(this, file_name)
      class(openai),    intent(inout) :: this
      character(len=*), intent(in)    :: file_name
      call this%set_file_name(trim(file_name))
      call this%load_api_key()
      call this%load_organization()
   end subroutine load_base_data
Call graph
load_base_data calls load_api_key, load_organization, set_file_name
load_api_key calls set_file_name, destroy, get, initialize, load_file
load_organization calls set_file_name, destroy, get, initialize, load_file