load_url – ForOpenAI
load_url Subroutine
Seyed Ali Ghasemi
12 statements
Source File
private impure elemental subroutine load_url(this)
Uses
json_module
Type Bound
ImageGeneration
Arguments
Type Intent Optional Attributes Name
class(ImageGeneration), intent(inout) :: this
Calls
Called by
Source Code
   elemental impure subroutine load_url(this)
      use json_module, only: json_file
      class(ImageGeneration), intent(inout) :: this
      type(json_file)                      :: json
      character(len=:), allocatable        :: tmp
      logical                              :: found
      call json%initialize()
      call json%load_file(trim(this%file_name))
      call json%get("ImageGeneration.url", tmp, found=found)
      if (found) this%url = trim(tmp)
      call json%destroy()
   end subroutine load_url
Call graph
load_url calls destroy, get, initialize, load_file
load_imagegeneration_data calls load_url
set_imagegeneration_data calls load_imagegeneration_data
test_imagegeneration calls set_imagegeneration_data