load_api_key – ForOpenAI
load_api_key Subroutine
Seyed Ali Ghasemi
11 statements
Source File
private impure elemental subroutine load_api_key(this, file_name)
Uses
json_module
Type Bound
openai
Arguments
Type Intent Optional Attributes Name
class(openai), intent(inout) :: this
character(len=*), intent(in), optional :: file_name
Calls
Called by
Source Code
   elemental impure subroutine load_api_key(this, file_name)
      use json_module, only: json_file
      class(openai),    intent(inout)        :: this
      character(len=*), intent(in), optional :: file_name
      type(json_file)                        :: json
      if (present(file_name)) call this%set_file_name(file_name)
      call json%initialize()
      call json%load_file(trim(this%file_name))
      call json%get("base.api_key", this%api_key)
      call json%destroy()
   end subroutine load_api_key
Call graph
load_api_key calls destroy, get, initialize, load_file, set_file_name
load_base_data calls load_api_key
set_base_data calls load_api_key
conversation calls set_base_data
test_base calls set_base_data
test_chatcompletion calls set_base_data
test_imagegeneration calls set_base_data
test_transcription calls set_base_data
test_translation calls set_base_data