load_ChatCompletion_data – ForOpenAI
load_ChatCompletion_data Subroutine
Seyed Ali Ghasemi
15 statements
Source File
private impure elemental subroutine load_ChatCompletion_data(this, file_name)
Type Bound
ChatCompletion
Arguments
Type Intent Optional Attributes Name
class(ChatCompletion), intent(inout) :: this
character(len=*), intent(in) :: file_name
Calls
Called by
Contents
Source Code
load_ChatCompletion_data
Source Code
   elemental impure subroutine load_ChatCompletion_data(this, file_name)
      class(ChatCompletion), intent(inout) :: this
      character(len=*),      intent(in)    :: file_name
      call this%set_file_name(trim(file_name))
      call this%load_url()
      call this%load_model()
      call this%load_user_name()
      call this%load_temperature()
      call this%load_presence_penalty()
      call this%load_frequency_penalty()
      call this%load_top_p()
      call this%load_n()
      call this%load_stream()
      call this%load_max_tokens()
   end subroutine load_ChatCompletion_data
Call graph
load_chatcompletion_data calls load_frequency_penalty, load_max_tokens, load_model, load_n, load_presence_penalty, load_stream, load_temperature, load_top_p, load_url, load_user_name, set_file_name
load_frequency_penalty calls destroy, get, initialize, load_file
load_max_tokens calls destroy, get, initialize, load_file
load_model calls destroy, get, initialize, load_file
load_n calls destroy, get, initialize, load_file
load_presence_penalty calls destroy, get, initialize, load_file
load_stream calls destroy, get, initialize, load_file
load_temperature calls destroy, get, initialize, load_file
load_top_p calls destroy, get, initialize, load_file
load_url calls destroy, get, initialize, load_file
load_user_name calls destroy, get, initialize, load_file
conversation calls load_chatcompletion_data