print_model_list – ForOpenAI
print_model_list Subroutine
Seyed Ali Ghasemi
8 statements
Source File
private impure elemental subroutine print_model_list(this)
Type Bound
ChatCompletion
Arguments
Type Intent Optional Attributes Name
class(ChatCompletion), intent(inout) :: this
Calls
Contents
Source Code
print_model_list
Source Code
   elemental impure subroutine print_model_list(this)
      class(ChatCompletion), intent(inout) :: this
      integer                              :: i
      call this%set_model_list()
      do i = 1, size(this%model_list)
         print "(I1,': ',A)",i,trim(this%model_list(i))
      end do
   end subroutine print_model_list
Call graph
print_model_list calls model_list, set_model_list
set_model_list calls model_list