read_user_message – ForOpenAI
read_user_message Subroutine
Seyed Ali Ghasemi
26 statements
Source File
private impure elemental subroutine read_user_message(this, file_name, command)
Uses
face
Type Bound
ChatCompletion
Arguments
Type Intent Optional Attributes Name
class(ChatCompletion), intent(inout) :: this
character(len=*), intent(in) :: file_name
character(len=*), intent(in) :: command
Calls
Called by
Contents
Source Code
read_user_message
Source Code
   elemental impure subroutine read_user_message(this, file_name, command)
      use face, only: colorize
      class(ChatCompletion),         intent(inout) :: this
      character(len=*),              intent(in)    :: file_name
      character(len=*),              intent(in)    :: command
      character(len=:), allocatable                :: message
      character(len=:), allocatable                :: whole_message
      character(len=1000000)                       :: tmp
      integer                                      :: iounit, iostat
      write(*,"(A,': ')",advance='no') colorize(trim(this%user_name), color_bg='green')
      read*, tmp
      message = trim(tmp)
      if (trim(message) == trim(command)) then
         open(newunit=iounit, file=trim(file_name), status='old', action='read')
         whole_message = ''
         do
            read(iounit,'(A)',iostat=iostat) tmp
            if (iostat /= 0) exit
            whole_message = trim(whole_message) // trim(tmp)  // new_line(' ')
         end do
         close(iounit)
         call this%set_user_message(message=whole_message)
      else
         call this%set_user_message(message=message)
      end if
   end subroutine read_user_message
Call graph
read_user_message calls colorize, set_user_message
set_user_message calls messages
conversation calls read_user_message