set_model_list – ForOpenAI
set_model_list Subroutine
Seyed Ali Ghasemi
12 statements
Source File
private pure elemental subroutine set_model_list(this)
Type Bound
ChatCompletion
Arguments
Type Intent Optional Attributes Name
class(ChatCompletion), intent(inout) :: this
Calls
Called by
Contents
Source Code
set_model_list
Source Code
   elemental pure subroutine set_model_list(this)
      class(ChatCompletion), intent(inout) :: this
      if (.not. allocated(this%model_list)) allocate(this%model_list(8))
      this%model_list(1) = trim('gpt-4')
      this%model_list(2) = trim('gpt-4-0613')
      this%model_list(3) = trim('gpt-4-32k')
      this%model_list(4) = trim('gpt-4-32k-0613')
      this%model_list(5) = trim('gpt-3.5-turbo')
      this%model_list(6) = trim('gpt-3.5-turbo-0613')
      this%model_list(7) = trim('gpt-3.5-turbo-16k')
      this%model_list(8) = trim('gpt-3.5-turbo-16k-0613')
   end subroutine set_model_list
Call graph
set_model_list calls model_list
print_model_list calls set_model_list
select_model calls set_model_list