set_ImageGeneration_data – ForOpenAI
set_ImageGeneration_data Subroutine
Seyed Ali Ghasemi
20 statements
Source File
private impure elemental subroutine set_ImageGeneration_data(this, file_name, url, size, prompt, response_format, n, user_name)
Type Bound
ImageGeneration
Arguments
Type Intent Optional Attributes Name
class(ImageGeneration), intent(inout) :: this
character(len=*), intent(in), optional :: file_name
character(len=*), intent(in), optional :: url
character(len=*), intent(in), optional :: size
character(len=*), intent(in), optional :: prompt
character(len=*), intent(in), optional :: response_format
integer, intent(in), optional :: n
character(len=*), intent(in), optional :: user_name
Calls
Called by
Source Code
   elemental impure subroutine set_ImageGeneration_data(this, file_name, &
      url, size, prompt, response_format, n, user_name)
      class(ImageGeneration),    intent(inout) :: this
      character(len=*), optional, intent(in)    :: file_name
      character(len=*), optional, intent(in)    :: url
      character(len=*), optional, intent(in)    :: size
      character(len=*), optional, intent(in)    :: prompt
      character(len=*), optional, intent(in)    :: response_format
      integer,          optional, intent(in)    :: n
      character(len=*), optional, intent(in)    :: user_name
      if (present(url)) call this%set_url(url=url)
      if (present(size)) call this%set_size(size=size)
      if (present(prompt)) call this%set_prompt(prompt=prompt)
      if (present(response_format)) call this%set_response_format(response_format=response_format)
      if (present(n)) call this%set_n(n=n)
      if (present(user_name)) call this%set_user_name(user_name=user_name)
      if (present(file_name)) then
         call this%set_file_name(file_name)
         call this%load(file_name)
      end if
   end subroutine set_ImageGeneration_data
Call graph
set_imagegeneration_data calls load_imagegeneration_data, set_file_name, set_n, set_prompt, set_response_format, set_size, set_url, set_user_name
load_imagegeneration_data calls set_file_name, load_n, load_response_format, load_size, load_url, load_user_name
load_n calls destroy, get, initialize, load_file
load_response_format calls destroy, get, initialize, load_file
load_size calls destroy, get, initialize, load_file
load_url calls destroy, get, initialize, load_file
load_user_name calls destroy, get, initialize, load_file
test_imagegeneration calls set_imagegeneration_data