set_Transcription_data – ForOpenAI
set_Transcription_data Subroutine
Seyed Ali Ghasemi
18 statements
Source File
private impure elemental subroutine set_Transcription_data(this, file_name, url, model, temperature, language, response_format)
Type Bound
Transcription
Arguments
Type Intent Optional Attributes Name
class(Transcription), intent(inout) :: this
character(len=*), intent(in), optional :: file_name
character(len=*), intent(in), optional :: url
character(len=*), intent(in), optional :: model
real, intent(in), optional :: temperature
character(len=*), intent(in), optional :: language
character(len=*), intent(in), optional :: response_format
Calls
Called by
Source Code
   elemental impure subroutine set_Transcription_data(this, file_name, &
      url, model, temperature, language, response_format)
      class(Transcription),       intent(inout) :: this
      character(len=*), optional, intent(in)    :: file_name
      character(len=*), optional, intent(in)    :: url
      character(len=*), optional, intent(in)    :: model
      real,             optional, intent(in)    :: temperature
      character(len=*), optional, intent(in)    :: language
      character(len=*), optional, intent(in)    :: response_format
      if (present(url)) call this%set_url(url=url)
      if (present(model)) call this%set_model(model=model)
      if (present(temperature)) call this%set_temperature(temperature=temperature)
      if (present(language)) call this%set_language(language=language)
      if (present(response_format)) call this%set_response_format(response_format=response_format)
      if (present(file_name)) then
         call this%set_file_name(file_name)
         call this%load(file_name)
      end if
   end subroutine set_Transcription_data
Call graph
set_transcription_data calls load_transcription_data, set_file_name, set_language, set_model, set_response_format, set_temperature, set_url
load_transcription_data calls set_file_name, load_language, load_model, load_response_format, load_temperature, load_url
load_language calls destroy, get, initialize, load_file
load_model calls destroy, get, initialize, load_file
load_response_format calls destroy, get, initialize, load_file
load_temperature calls destroy, get, initialize, load_file
load_url calls destroy, get, initialize, load_file
test_transcription calls set_transcription_data