set_base_data – ForOpenAI
set_base_data Subroutine
Seyed Ali Ghasemi
14 statements
Source File
private impure elemental subroutine set_base_data(this, file_name, api_key, organization)
Type Bound
openai
Arguments
Type Intent Optional Attributes Name
class(openai), intent(inout) :: this
character(len=*), intent(in), optional :: file_name
character(len=*), intent(in), optional :: api_key
character(len=*), intent(in), optional :: organization
Calls
Called by
Source Code
   elemental impure subroutine set_base_data(this, file_name, api_key, organization)
      class(openai),              intent(inout) :: this
      character(len=*), optional, intent(in)    :: file_name
      character(len=*), optional, intent(in)    :: api_key
      character(len=*), optional, intent(in)    :: organization
      integer                                   :: stat_api_key, stat_organization
      if (present(api_key)) call this%set_api_key(api_key)
      if (present(organization)) call this%set_organization(organization)
      if (present(file_name)) call this%set_file_name(file_name)
      call this%set_api_key_env(status=stat_api_key)
      if (stat_api_key == 1) call this%load_api_key(file_name)
      call this%set_organization_env(status=stat_organization)
      if (stat_organization == 1) call this%load_organization(file_name)
   end subroutine set_base_data
Call graph
set_base_data calls load_api_key, load_organization, set_api_key, set_api_key_env, set_file_name, set_organization, set_organization_env
load_api_key calls set_file_name, destroy, get, initialize, load_file
load_organization calls set_file_name, destroy, get, initialize, load_file
set_api_key_env calls set_api_key
set_organization_env calls set_organization
conversation calls set_base_data
test_base calls set_base_data
test_chatcompletion calls set_base_data
test_imagegeneration calls set_base_data
test_transcription calls set_base_data
test_translation calls set_base_data