set_api_key_env – ForOpenAI
set_api_key_env Subroutine
Seyed Ali Ghasemi
7 statements
Source File
private impure elemental subroutine set_api_key_env(this, status)
Type Bound
openai
Arguments
Type Intent Optional Attributes Name
class(openai), intent(inout) :: this
integer, intent(out), optional :: status
Calls
Called by
Source Code
   elemental impure subroutine set_api_key_env(this, status)
      class(openai), intent(inout)         :: this
      integer,       intent(out), optional :: status
      character(len=1024)                  :: tmp
      call get_environment_variable(this%api_key_env, tmp, status = status)
      if (status==0) call this%set_api_key(trim(tmp))
   end subroutine set_api_key_env
Call graph
set_api_key_env calls set_api_key
set_base_data calls set_api_key_env
conversation calls set_base_data
test_base calls set_base_data
test_chatcompletion calls set_base_data
test_imagegeneration calls set_base_data
test_transcription calls set_base_data
test_translation calls set_base_data