set_user_message – ForOpenAI
set_user_message Subroutine
Seyed Ali Ghasemi
10 statements
Source File
private pure elemental subroutine set_user_message(this, message)
Type Bound
ChatCompletion
Arguments
Type Intent Optional Attributes Name
class(ChatCompletion), intent(inout) :: this
character(len=*), intent(in) :: message
Calls
Called by
Contents
Source Code
set_user_message
Source Code
   elemental pure subroutine set_user_message(this, message)
      class(ChatCompletion), intent(inout) :: this
      character(len=*),      intent(in)    :: message
      integer                              :: i
      do i = 1, size(this%messages)
         if (this%messages(i)%role == 'user') then
            call this%messages(i)%set_content(content=message)
         end if
      end do
   end subroutine set_user_message
Call graph
set_user_message calls messages
read_user_message calls set_user_message
conversation calls read_user_message