set_ChatCompletion_data – ForOpenAI
set_ChatCompletion_data Subroutine
Seyed Ali Ghasemi
28 statements
Source File
private impure elemental subroutine set_ChatCompletion_data(this, file_name, url, model, user_name, temperature, presence_penalty, frequency_penalty, top_p, n, stream, max_tokens)
Type Bound
ChatCompletion
Arguments
Type Intent Optional Attributes Name
class(ChatCompletion), intent(inout) :: this
character(len=*), intent(in), optional :: file_name
character(len=*), intent(in), optional :: url
character(len=*), intent(in), optional :: model
character(len=*), intent(in), optional :: user_name
real, intent(in), optional :: temperature
real, intent(in), optional :: presence_penalty
real, intent(in), optional :: frequency_penalty
real, intent(in), optional :: top_p
integer, intent(in), optional :: n
logical, intent(in), optional :: stream
integer, intent(in), optional :: max_tokens
Calls
Called by
Source Code
   elemental impure subroutine set_ChatCompletion_data(this, file_name, &
      url, model, user_name, temperature, presence_penalty, frequency_penalty, top_p, n, stream, max_tokens)
      class(ChatCompletion),      intent(inout) :: this
      character(len=*), optional, intent(in)    :: file_name
      character(len=*), optional, intent(in)    :: url
      character(len=*), optional, intent(in)    :: model
      character(len=*), optional, intent(in)    :: user_name
      real,             optional, intent(in)    :: temperature
      real,             optional, intent(in)    :: presence_penalty
      real,             optional, intent(in)    :: frequency_penalty
      real,             optional, intent(in)    :: top_p
      integer,          optional, intent(in)    :: n
      logical,          optional, intent(in)    :: stream
      integer,          optional, intent(in)    :: max_tokens
      if (present(url)) call this%set_url(url=url)
      if (present(model)) call this%set_model(model=model)
      if (present(user_name)) call this%set_user_name(user_name=user_name)
      if (present(temperature)) call this%set_temperature(temperature=temperature)
      if (present(presence_penalty)) call this%set_presence_penalty(presence_penalty=presence_penalty)
      if (present(frequency_penalty)) call this%set_frequency_penalty(frequency_penalty=frequency_penalty)
      if (present(top_p)) call this%set_top_p(top_p=top_p)
      if (present(n)) call this%set_n(n=n)
      if (present(stream)) call this%set_stream(stream=stream)
      if (present(max_tokens)) call this%set_max_tokens(max_tokens=max_tokens)
      if (present(file_name)) then
         call this%set_file_name(file_name)
         call this%load(file_name)
      end if
   end subroutine set_ChatCompletion_data
Call graph
set_chatcompletion_data calls load_chatcompletion_data, set_file_name, set_frequency_penalty, set_max_tokens, set_model, set_n, set_presence_penalty, set_stream, set_temperature, set_top_p, set_url, set_user_name
load_chatcompletion_data calls set_file_name, load_frequency_penalty, load_max_tokens, load_model, load_n, load_presence_penalty, load_stream, load_temperature, load_top_p, load_url, load_user_name
load_frequency_penalty calls destroy, get, initialize, load_file
load_max_tokens calls destroy, get, initialize, load_file
load_model calls destroy, get, initialize, load_file
load_n calls destroy, get, initialize, load_file
load_presence_penalty calls destroy, get, initialize, load_file
load_stream calls destroy, get, initialize, load_file
load_temperature calls destroy, get, initialize, load_file
load_top_p calls destroy, get, initialize, load_file
load_url calls destroy, get, initialize, load_file
load_user_name calls destroy, get, initialize, load_file
conversation calls set_chatcompletion_data
test_chatcompletion calls set_chatcompletion_data