set_file_name – ForOpenAI
set_file_name Subroutine
Seyed Ali Ghasemi
5 statements
Source File
private pure elemental subroutine set_file_name(this, file_name)
Type Bound
openai
Arguments
Type Intent Optional Attributes Name
class(openai), intent(inout) :: this
character(len=*), intent(in) :: file_name
Called by
Source Code
   elemental pure subroutine set_file_name(this, file_name)
      class(openai),    intent(inout) :: this
      character(len=*), intent(in)    :: file_name
      this%file_name = trim(file_name)
   end subroutine set_file_name
Call graph
load_api_key calls set_file_name
load_base_data calls set_file_name, load_api_key, load_organization
load_chatcompletion_data calls set_file_name
load_imagegeneration_data calls set_file_name
load_organization calls set_file_name
load_transcription_data calls set_file_name
load_translation_data calls set_file_name
set_base_data calls set_file_name, load_api_key, load_organization
set_chatcompletion_data calls set_file_name, load_chatcompletion_data
set_imagegeneration_data calls set_file_name, load_imagegeneration_data
set_transcription_data calls set_file_name, load_transcription_data
set_translation_data calls set_file_name, load_translation_data
conversation calls set_base_data, set_chatcompletion_data
test_base calls set_base_data
test_chatcompletion calls set_base_data, set_chatcompletion_data
test_imagegeneration calls set_base_data, set_imagegeneration_data
test_transcription calls set_base_data, set_transcription_data
test_translation calls set_base_data, set_translation_data