set_organization – ForOpenAI
set_organization Subroutine
Seyed Ali Ghasemi
5 statements
Source File
private pure elemental subroutine set_organization(this, organization)
Type Bound
openai
Arguments
Type Intent Optional Attributes Name
class(openai), intent(inout) :: this
character(len=*), intent(in) :: organization
Called by
Source Code
   elemental pure subroutine set_organization(this, organization)
      class(openai),    intent(inout) :: this
      character(len=*), intent(in)    :: organization
      this%organization = trim(organization)
   end subroutine set_organization
Call graph
set_base_data calls set_organization, set_organization_env
set_organization_env calls set_organization
conversation calls set_base_data
test_base calls set_base_data
test_chatcompletion calls set_base_data
test_imagegeneration calls set_base_data
test_transcription calls set_base_data
test_translation calls set_base_data