set_Translation_data – ForOpenAI
set_Translation_data Subroutine
Seyed Ali Ghasemi
16 statements
Source File
private impure elemental subroutine set_Translation_data(this, file_name, url, model, temperature, response_format)
Type Bound
Translation
Arguments
Type Intent Optional Attributes Name
class(Translation), intent(inout) :: this
character(len=*), intent(in), optional :: file_name
character(len=*), intent(in), optional :: url
character(len=*), intent(in), optional :: model
real, intent(in), optional :: temperature
character(len=*), intent(in), optional :: response_format
Calls
Called by
Source Code
   elemental impure subroutine set_Translation_data(this, file_name, &
      url, model, temperature, response_format)
      class(Translation),         intent(inout) :: this
      character(len=*), optional, intent(in)    :: file_name
      character(len=*), optional, intent(in)    :: url
      character(len=*), optional, intent(in)    :: model
      real,             optional, intent(in)    :: temperature
      character(len=*), optional, intent(in)    :: response_format
      if (present(url)) call this%set_url(url=url)
      if (present(model)) call this%set_model(model=model)
      if (present(temperature)) call this%set_temperature(temperature=temperature)
      if (present(response_format)) call this%set_response_format(response_format=response_format)
      if (present(file_name)) then
         call this%set_file_name(file_name)
         call this%load(file_name)
      end if
   end subroutine set_Translation_data
Call graph
set_translation_data calls load_translation_data, set_file_name, set_model, set_response_format, set_temperature, set_url
load_translation_data calls set_file_name, load_model, load_response_format, load_temperature, load_url
load_model calls destroy, get, initialize, load_file
load_response_format calls destroy, get, initialize, load_file
load_temperature calls destroy, get, initialize, load_file
load_url calls destroy, get, initialize, load_file
test_translation calls set_translation_data