set_ImageEdit_data – ForOpenAI
set_ImageEdit_data Subroutine
Seyed Ali Ghasemi
18 statements
Source File
private impure elemental subroutine set_ImageEdit_data(this, file_name, url, size, response_format, n, user_name)
Type Bound
ImageEdit
Arguments
Type Intent Optional Attributes Name
class(ImageEdit), intent(inout) :: this
character(len=*), intent(in), optional :: file_name
character(len=*), intent(in), optional :: url
character(len=*), intent(in), optional :: size
character(len=*), intent(in), optional :: response_format
integer, intent(in), optional :: n
character(len=*), intent(in), optional :: user_name
Calls
Contents
Source Code
set_ImageEdit_data
Source Code
   elemental impure subroutine set_ImageEdit_data(this, file_name, &
      url, size, response_format, n, user_name)
      class(ImageEdit),           intent(inout) :: this
      character(len=*), optional, intent(in)    :: file_name
      character(len=*), optional, intent(in)    :: url
      character(len=*), optional, intent(in)    :: size
      character(len=*), optional, intent(in)    :: response_format
      integer,          optional, intent(in)    :: n
      character(len=*), optional, intent(in)    :: user_name
      if (present(url)) call this%set_url(url=url)
      if (present(size)) call this%set_size(size=size)
      if (present(response_format)) call this%set_response_format(response_format=response_format)
      if (present(n)) call this%set_n(n=n)
      if (present(user_name)) call this%set_user_name(user_name=user_name)
      if (present(file_name)) then
         call this%set_file_name(file_name)
         call this%load(file_name)
      end if
   end subroutine set_ImageEdit_data
Call graph
set_imageedit_data calls load, set_n, set_response_format, set_size, set_url, set_user_name, set_file_name