test_ChatCompletion – ForOpenAI
test_ChatCompletion Program
16 statements
Source File
Uses
foropenai
Calls
Variables
Type Attributes Name Initial
type(ChatCompletion) :: chat
Source Code
program test_ChatCompletion
   use foropenai, only: ChatCompletion
   implicit none
   type(ChatCompletion) :: chat
   call chat%set_base_data(file_name='foropenai.json')
   call chat%set(file_name='foropenai.json')
   call chat%init_messages(n=3)
   call chat%messages(1)%set(role='system', content='You are a helpful assistant.')
   call chat%messages(2)%set(role='user', content='Hello?')
   call chat%messages(3)%set(role='assistant', content='')
   call chat%print_user_message()
   call chat%create()
   call chat%print_assistant_response()
   call chat%usage%print()
   call chat%finalize()
end program test_ChatCompletion
Call graph
test_chatcompletion calls create_chat_completion, deallocate_chatcompletion, init_messages, print_assistant_response, print_user_message, set_base_data, set_chatcompletion_data
create_chat_completion calls add, deserialize, destroy, get, initialize, pair_type, print_to_string, check_chat_completion, set_asisstant_response, request
deallocate_chatcompletion calls deallocate_finish_reason, deallocate_messages, deallocate_model, deallocate_model_list, deallocate_url, deallocate_user_name
print_assistant_response calls colorize
print_user_message calls colorize
set_base_data calls load_api_key, load_organization, set_api_key, set_api_key_env, set_file_name, set_organization, set_organization_env
set_chatcompletion_data calls load_chatcompletion_data, set_file_name, set_frequency_penalty, set_max_tokens, set_model, set_n, set_presence_penalty, set_stream, set_temperature, set_top_p, set_url, set_user_name
load_api_key calls destroy, get, initialize, set_file_name, load_file
load_chatcompletion_data calls set_file_name, load_frequency_penalty, load_max_tokens, load_model, load_n, load_presence_penalty, load_stream, load_temperature, load_top_p, load_url, load_user_name
load_organization calls destroy, get, initialize, set_file_name, load_file
set_api_key_env calls set_api_key
set_asisstant_response calls set_content
set_organization_env calls set_organization
load_frequency_penalty calls destroy, get, initialize, load_file
load_max_tokens calls destroy, get, initialize, load_file
load_model calls destroy, get, initialize, load_file
load_n calls destroy, get, initialize, load_file
load_presence_penalty calls destroy, get, initialize, load_file
load_stream calls destroy, get, initialize, load_file
load_temperature calls destroy, get, initialize, load_file
load_top_p calls destroy, get, initialize, load_file
load_url calls destroy, get, initialize, load_file
load_user_name calls destroy, get, initialize, load_file