test_ImageGeneration – ForOpenAI
test_ImageGeneration Program
11 statements
Source File
Uses
foropenai
Calls
Variables
Type Attributes Name Initial
type(ImageGeneration) :: image
Source Code
program test_ImageGeneration
   use foropenai, only: ImageGeneration
   implicit none
   type(ImageGeneration) :: image
   call image%set_base_data(file_name='foropenai.json')
   call image%set(file_name='foropenai.json')
   call image%create(prompt='a cat with a computer')
   call image%print_prompt()
   call image%print_assistant_response()
   call image%finalize()
end program test_ImageGeneration
Call graph
test_imagegeneration calls create_image, deallocate_imagegeneration, print_assistant_response, print_prompt, set_base_data, set_imagegeneration_data
create_image calls add, deserialize, destroy, get, initialize, pair_type, print_to_string, set_assistant_response, set_n, set_prompt, set_response_format, set_size, set_user_name, request
deallocate_imagegeneration calls deallocate_assistant_response, deallocate_url, deallocate_user_name
print_assistant_response calls colorize
print_prompt calls colorize
set_base_data calls load_api_key, load_organization, set_api_key, set_api_key_env, set_file_name, set_organization, set_organization_env
set_imagegeneration_data calls load_imagegeneration_data, set_file_name, set_n, set_prompt, set_response_format, set_size, set_url, set_user_name
load_api_key calls destroy, get, initialize, set_file_name, load_file
load_imagegeneration_data calls set_file_name, load_n, load_response_format, load_size, load_url, load_user_name
load_organization calls destroy, get, initialize, set_file_name, load_file
set_api_key_env calls set_api_key
set_organization_env calls set_organization
load_n calls destroy, get, initialize, load_file
load_response_format calls destroy, get, initialize, load_file
load_size calls destroy, get, initialize, load_file
load_url calls destroy, get, initialize, load_file
load_user_name calls destroy, get, initialize, load_file