test_Translation – ForOpenAI
test_Translation Program
11 statements
Source File
Uses
foropenai
Calls
Variables
Type Attributes Name Initial
type(Translation) :: trs
Source Code
program test_Translation
   use foropenai, only: Translation
   implicit none
   type(Translation) :: trs
   call trs%set_base_data(file_name='foropenai.json')
   call trs%set(file_name='foropenai.json')
   call trs%create(file='test/audio_de.mp3')
   call trs%print_file()
   call trs%print_assistant_response()
   call trs%finalize()
end program test_Translation
Call graph
test_translation calls create_translation, deallocate_translation, print_assistant_response, print_file, set_base_data, set_translation_data
create_translation calls deserialize, destroy, get, initialize, pair_type, set_file, set_prompt, request
deallocate_translation calls deallocate_assistant_response, deallocate_file, deallocate_model, deallocate_prompt, deallocate_url
print_assistant_response calls colorize
print_file calls colorize
set_base_data calls load_api_key, load_organization, set_api_key, set_api_key_env, set_file_name, set_organization, set_organization_env
set_translation_data calls load_translation_data, set_file_name, set_model, set_response_format, set_temperature, set_url
load_api_key calls destroy, get, initialize, set_file_name, load_file
load_organization calls destroy, get, initialize, set_file_name, load_file
load_translation_data calls set_file_name, load_model, load_response_format, load_temperature, load_url
set_api_key_env calls set_api_key
set_organization_env calls set_organization
load_model calls destroy, get, initialize, load_file
load_response_format calls destroy, get, initialize, load_file
load_temperature calls destroy, get, initialize, load_file
load_url calls destroy, get, initialize, load_file