test_base – ForOpenAI
test_base Program
10 statements
Source File
Uses
foropenai
Calls
Variables
Type Attributes Name Initial
type(openai) :: base
Source Code
program test_base
   use foropenai, only: openai
   implicit none
   type(openai) :: base
   call base%set_base_data(file_name='foropenai.json')
   call base%print_api_key()
   call base%print_organization()
   call base%print_file_name()
   call base%finalize()
end program test_base
Call graph
test_base calls deallocate_openai, print_api_key, print_file_name, print_organization, set_base_data
deallocate_openai calls deallocate_api_key, deallocate_file_name, deallocate_organization
set_base_data calls load_api_key, load_organization, set_api_key, set_api_key_env, set_file_name, set_organization, set_organization_env
load_api_key calls set_file_name, destroy, get, initialize, load_file
load_organization calls set_file_name, destroy, get, initialize, load_file
set_api_key_env calls set_api_key
set_organization_env calls set_organization