test_Transcription – ForOpenAI
test_Transcription Program
11 statements
Source File
Uses
foropenai
Calls
Variables
Type Attributes Name Initial
type(Transcription) :: trs
Source Code
program test_Transcription
   use foropenai, only: Transcription
   implicit none
   type(Transcription) :: trs
   call trs%set_base_data(file_name='foropenai.json')
   call trs%set(file_name='foropenai.json')
   call trs%create(file='test/audio.mp3')
   call trs%print_file()
   call trs%print_assistant_response()
   call trs%finalize()
end program test_Transcription
Call graph
test_transcription calls create_transcription, deallocate_transcription, print_assistant_response, print_file, set_base_data, set_transcription_data
create_transcription calls deserialize, destroy, get, initialize, pair_type, set_file, set_prompt, request
deallocate_transcription calls deallocate_assistant_response, deallocate_file, deallocate_language, deallocate_model, deallocate_prompt, deallocate_url
print_assistant_response calls colorize
print_file calls colorize
set_base_data calls load_api_key, load_organization, set_api_key, set_api_key_env, set_file_name, set_organization, set_organization_env
set_transcription_data calls load_transcription_data, set_file_name, set_language, set_model, set_response_format, set_temperature, set_url
load_api_key calls destroy, get, initialize, set_file_name, load_file
load_organization calls destroy, get, initialize, set_file_name, load_file
load_transcription_data calls set_file_name, load_language, load_model, load_response_format, load_temperature, load_url
set_api_key_env calls set_api_key
set_organization_env calls set_organization
load_language calls destroy, get, initialize, load_file
load_model calls destroy, get, initialize, load_file
load_response_format calls destroy, get, initialize, load_file
load_temperature calls destroy, get, initialize, load_file
load_url calls destroy, get, initialize, load_file